# Generated by Django 2.2.5 on 2019-10-02 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_auto_20191002_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
