# Generated by Django 2.2.5 on 2019-10-02 00:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_auto_20191002_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2019, 10, 2, 0, 23, 13, 60112)),
        ),
    ]
